### ISSUE TITLE
HMC NaN warning message

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#13]
A couple  thoughts about the warning of NaN when initializing HMC:

1. I think it should be printed as complete sentences with a period at the end of a given line. (and same comment about the note about HMC using X warmup iterations). 
2. It references `timesRan` which is a bit hard to understand for a user.  
3. "; recommend better initial values" is a bit ungrammatical and "reducing initial step-size" appears as its own line.
4. I think "step-size" should be "step size".

```
[Note] HMC sampler (nodes: mu0, sigma, rho, beta, w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8], w[9], w[10], w[11], w[12],...) is using 750 warmup iterations
|-------------|-------------|-------------|-------------|
|  [Warning] HMC sampler (nodes: mu0, sigma, rho, beta, w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8], w[9], w[10], w[11], w[12],...) encountered a NaN value in leapfrog routine, with timesRan = 0
  [Warning] HMC sampler (nodes: mu0, sigma, rho, beta, w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8], w[9], w[10], w[11], w[12],...) encountered NaN while initializing step-size; recommend better initial values
            reducing initial step-size
-------------------------------------------------------|
```

@danielturek would you be up for some cleanup here? I'm also happy to do it.

**Comment by paciorek** [comment]
Also, we need periods at the end of the max tree depth and divergent path [Note]s to be consistent with our other [Note]s.

**Comment by danielturek** [comment]
@paciorek I have revamped the system of warnings in the HMC sampler.  Critically,

1. All warnings are now printed at the **end** of the MCMC chain.
2. I lowered the default number of warnings from 5 down to 0.  It still prints the diagnostics about number of divergences, and times the max tree depth is reached.  But the warnings, such as "encountered NaN in epsilon", etc, be default are turned off.  One can enable these by setting `numWarnings = 5`, or whatever, and they will be printed at the end of the chain.

How does this sound?

**Comment by danielturek** [comment]
@paciorek Yes, that's the thing - I don't think the warnings are something to cause concern.  They occur when the stepsize (epsilon) is too large, and the "numerical integration" tracing out a discrete-time trajectory in parameter space based upon (take local derivative) (step) (take local derivative) (step) procedure steps too far in some direction (stepsize is too large), and thus arrives at a numerically intractable location (I know the parameter transformation makes the working-space unconstrained, but this can still happen, e.g. back-transforming something that's too far in some direction can round down to 0).  Anyway, these are "normal" happenings in the discrete-time leapfrog process, and these cases are handled in stride by adapting (in this case, reducing) the stepsize.  So that's why I kind feel the warnings are unnecessary.

**Comment by paciorek** [comment]
Ok, good you have a handle on this. I think the roxygen could better reflect what you said in your note here to give the user a bit more info (perhaps a section of the roxygen?). And I'm happy with `numWarnings=0` given that.

**Comment by danielturek** [comment]
@paciorek Updated the HMC documentation accordingly.
