### ISSUE TITLE
"Error: must set buildDerivs = TRUE when building model" when the model is created using `readBUGSmodel()`

### ISSUE THREAD

**Issue by pehkawn** [nimble-dev/nimbleHMC#39]
According to the Nimble user guide, automatic differentiation (AD) is needed when using HMC. When building a model using `nimbleModel()`, AD can be enabled by setting thefunction argument `buildDerivs = TRUE`. However, when building the model using `readBUGSmodel()`, there's seemingly no option for enabling AD. 

Consequentially, I get the error message:
``` 
Error: must set buildDerivs = TRUE when building model
```
when running `nimbleHMC()` on my BUGS model.

I was therefore wondering if there's another way of enabling AD, when reading in a BUGS model file? 

As a feature suggestion, it would be an improvement if `buildDerivs` were to be added to available options in either `nimbleHMC()` or `readBUGSmodel()`.

**Comment by danielturek** [comment]
@pehkawn I agree with your assessment and request, and thanks for posting the issue.

I'm going to close the issue here, can you please post the same issue in the `nimble-dev/nimble` repository, which houses the relevant `nimbleModel` and `readBUGSmodel` functions?  That's where this issue truly belongs.

**Comment by pehkawn** [comment]
Thank you for your reply. I will post the issue there.
